---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-confd
description: Install confd through ansible
tags:
  - ansible
  - ansible-role
  - confd
github:
  has_issues: true
  has_projects: false
  has_wiki: false
